### ISSUE TITLE
Markdownの導入に当たっての調査

### ISSUE THREAD

**Issue by sunecosuri** [pepabo-college/migacode#24]
## 概要
当初から予定していたMarkdown機能の実装に取り組むため調査を実施したいと思います。

## クローズ条件
Markdown機能の導入のやり方が分かりWIPプルリクに必要な手順をTODOとして記載できること。

**Comment by sunecosuri** [comment]
Markdownのgem色々あるけど（qiita-markdownとか）red carpetってgemがシンプルそうなのでこれに決定
https://github.com/vmg/redcarpet

公式見る限りインタンスメソッド呼び出せば変換してくれる
```
markdown = Redcarpet::Markdown.new(renderer, extensions = {})
markdown.render("This is *bongos*, indeed.")
```

```
<p>This is <em>bongos</em>, indeed.</p>
```

**Comment by bake0937** [comment]
ココらへんの記事とかも参考になるかもです
[ [Rails] Markdown形式で入力できるようにしてみた（シンタックスハイライトも対応）](http://qiita.com/hkengo/items/978ea1874cf7e07cdbfc)

**Comment by sunecosuri** [comment]
基本的に公式が提供しているOptionでほぼほぼ実現できそうですね…
ひとまずtodo作ります。

**Comment by bake0937** [comment]
こんな感じのプレビュー画面も出来たら良いですね(あくまでイメージです)
[Demo](http://mizchi.github.io/md2react/)
https://github.com/mizchi/md2react

**Comment by sunecosuri** [comment]
具体的な仕様の要望だ…しかもペパカレで学んだreact…僥倖…
まずは導入して、別のissueにある「viewの装飾について」でスケジュール確認しながら話しましょう

**Comment by sunecosuri** [comment]
ひとまず、やり方と手順が整理できて条件満たしたのでcloseします
